ALTER TABLE cars ADD COLUMN IF NOT EXISTS daily_rate_cents INTEGER NOT NULL DEFAULT 5000;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS odometer INTEGER NOT NULL DEFAULT 0;

ALTER TABLE bookings ADD COLUMN IF NOT EXISTS final_odometer INTEGER;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS damage_cost_cents INTEGER DEFAULT 0;
